# docker-compose.yml
# https://dev.to/ishankhare07/nginx-as-reverse-proxy-for-a-flask-app-using-docker-3ajg
version: '3'
services: 
  movies:
    image: movies-app
    container_name: movies
    build:
      context: .
      dockerfile: Dockerfile_movies
    networks:
      movies-network:
          aliases:
              - movies-app
    ports:
      - "8080:5000"
    volumes:
      - "./:/app"
    links:
      - "db_movies:db_movies"
 
  db_movies:
    image: mysql:5.7
    container_name: db_movies
    networks:
      movies-network:
          aliases:
              - db_movies
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies
      MYSQL_USER: movies
      MYSQL_PASSWORD: movies

networks:
  movies-network:
  
  